#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri May 08 19:31:03 KST 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_unified_butterfly2_top_behav -key {Behavioral:sim_1:Functional:tb_unified_butterfly2_top} -tclbatch tb_unified_butterfly2_top.tcl -view /home/pacl/unified_butterfly2/tb_unified_butterfly2_top_behav.wcfg -log simulate.log"
xsim tb_unified_butterfly2_top_behav -key {Behavioral:sim_1:Functional:tb_unified_butterfly2_top} -tclbatch tb_unified_butterfly2_top.tcl -view /home/pacl/unified_butterfly2/tb_unified_butterfly2_top_behav.wcfg -log simulate.log

